### ISSUE TITLE
Task List 

### ISSUE THREAD

**Issue by Timothyoung97** [Timothyoung97/RenderingEngine#2]
### Pending

- [ ] Space Partitioning
  - Quad/Oct tree scene partitioning
  - Initial Support for static objects only
  - Leaf Node Broad-Phase culling per view-proj
  - Per Instance fine-grained frustum culling after

- [ ] Spherical Environment Mapping
  - Essentially a non-hardcoded ambient term contribution
  - https://www.clicktorelease.com/blog/creating-spherical-environment-mapping-shader/

- [ ] PBR Rendering
  - Energy conserving for Diffuse
  - Microfacet surface model for Specular
  - Physically based BRDF (Bidirectional Reflective Distribution Function)

- [ ] Shadows for Point Lights

- [ ] Height-map-based terrain rendering
  - Start with high detail CPU-generated mesh
  - Render with multiple TriangleStrip draw calls
  - Optimize with a single Indirect Draw Call
  - Move on to Tesselated GPU-Driven terrain rendering
  - Biome/Height/Steepness based Terrain Albedo

- [ ] Image Based Lighting
  - Physically correct variant of Spherical Environment Mapping

- [ ] Extend Space Partition to dynamic objects
- [ ] Static Animations
- [ ] Skinning
